version: "3.7"
services:
  points:
    container_name: nest-starter-project
    build: .
    image: nest-starter-project:1.0.0
    ports:
      - "3000:3000"
    environment:
      - APPLICATION_NAME=${APPLICATION_NAME:-"nest-starter-project"}
      - NODE_ENV=${NODE_ENV:-development}
      - SERVER_ENV=${SERVER_ENV:-development}
      - PORT=${PORT:-3000}
      - DB_HOST=${DB_HOST:?err}
      - DB_NAME=${DB_NAME:?err}
      - DB_PORT=${DB_PORT:?err}
      - DB_USER=${DB_USER:?err}
      - DB_PASSWORD=${DB_PASSWORD:?err}